var data = [
  {
    name: "Arsenal",
    founded: 1886,
    address: "Emirates Stadium",
    logo:
      "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/800px-Arsenal_FC.svg.png",
    players: [
      { 1: "Bernd Leno" },
      { 13: "Rúnar Alex Rúnarsson" },
      { 44: "Karl Hein" },
      { 33: "Mat Ryan" },
      { 53: "Arthur Okonkwo" },
      { 45: "James Hillson" },
      { 2: "Héctor Bellerín" },
      { 3: "Kieran Tierney" },
      { 16: "Rob Holding" },
      { 21: "Calum Chambers" },
      { 23: "David Luiz" },
      { 6: "Gabriel Magalhães" },
      { 17: "Cédric Soares" },
      { 22: "Pablo Marí" },
      { 49: "Joel Lopez Salguero" },
      { 25: "Mohamed Elneny" },
      { 32: "Emile Smith Rowe" },
      { 34: "Granit Xhaka" },
      { 7: "Bukayo Saka" },
      { 18: "Thomas Partey" },
      { 11: "Martin Ødegaard" },
      { 41: "Ben Cottrell" },
      { 66: "Miguel Azeez" },
      { 8: "Dani Ceballos" },
      { 9: "Alexandre Lacazette" },
      { 14: "Pierre-Emerick Aubameyang" },
      { 19: "Nicolas Pépé" },
      { 24: "Reiss Nelson" },
      { 30: "Eddie Nketiah" },
      { 35: "Gabriel Martinelli" },
      { 12: "Willian" },
      { 38: "Folarin Balogun" },
    ],
  },
  {
    name: "Bayern Munich",
    founded: 1900,
    address: "Allianz Arena",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/800px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png",
    players: [
      { 1: "Manuel Neuer" },
      { 4: "Niklas Süle" },
      { 5: "Benjamin Pavard" },
      { 6: "Joshua Kimmich" },
      { 7: "Serge Gnabry" },
      { 9: "Robert Lewandowski" },
      { 8: "Javi Martínez" },
      { 10: "Leroy Sané" },
      { 11: "Douglas Costa" },
      { 13: "Eric Maxim Choupo-Moting" },
      { 17: "Jérôme Boateng " },
      { 18: "Leon Goretzka " },
      { 19: "AlphonsoDavies" },
      { 20: "Bouna Sarr" },
      { 21: "Lucas Hernandez" },
      { 22: "Marc Roca" },
      { 23: "Tanguy Nianzou" },
      { 24: "Corentin Tolisso " },
      { 25: "Thomas Müller " },
      { 27: "David Alaba " },
      { 29: "Kingsley Coman" },
      { 35: "Alexander Nübel " },
      { 42: "Jamal Musiala" },
    ],
  },
  {
    name: "Real Madrid",
    founded: 1902,
    address: "Estadio Santiago Bernabéu",
    logo:
      "https://tipsmake.com/data/images/collection-of-the-most-beautiful-football-logos-picture-2-sBRqpsGAd.jpg",
    players: [
      { 2: "Dani Carvajal" },
      { 3: "Éder Militão" },
      { 4: "Sergio Ramos " },
      { 5: "Raphaël Varane" },
      { 6: "Nacho" },
      { 7: "Eden Hazard" },
      { 8: "Toni Kroos" },
      { 9: "Karim Benzema " },
      { 10: "Luka Modrić" },
      { 11: "Marco Asensio" },
      { 12: "Marcelo" },
      { 13: "Andriy Lunin" },
      { 14: "Casemiro" },
      { 15: "Federico Valverde" },
      { 17: "Lucas Vázquez" },
      { 19: "Álvaro Odriozola" },
      { 20: "Vinícius Júnior" },
      { 22: "Isco" },
      { 23: "Ferland Mendy" },
      { 24: "Mariano" },
      { 25: "Rodrygo" },
    ],
  },
  {
    name: "Liverpool",
    founded: 1892,
    address: "Anfield",
    logo: "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
    players: [
      { 1: "Alisson" },
      { 3: "Fabinho" },
      { 4: "Virgil van Dijk" },
      { 5: "Georginio Wijnaldum" },
      { 6: "Thiago Alcântara" },
      { 7: "James Milner" },
      { 8: "Naby Keïta" },
      { 9: "Roberto Firmino" },
      { 10: "Sadio Mané" },
      { 11: "Mohamed Salah" },
      { 12: "Joe Gomez" },
      { 13: "Adrián" },
      { 14: "Jordan Henderson" },
      { 15: "Alex Oxlade-Chamberlain" },
      { 17: "Curtis Jones" },
      { 19: "Ozan Kabak " },
      { 20: "Diogo Jota" },
      { 21: "Kostas Tsimikas" },
      { 23: "Xherdan Shaqiri" },
      { 26: "Andrew Robertson" },
      { 27: "Divock Origi" },
      { 28: "Ben Davies" },
      { 32: "Joël Matip" },
      { 46: "Rhys Williams" },
      { 47: "Nathaniel Phillips" },
      { 58: "Ben Woodburn" },
      { 62: "Caoimhín Kelleher" },
      { 66: "Trent Alexander-Arnold" },
      { 76: "Neco Williams" },
    ],
  },
  {
    name: "Barcelona",
    founded: 1899,
    address: "Camp Nou",
    logo:
      "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg",
    players: [
      { 1: "Marc-AndréterStegen" },
      { 2: "SergiñoDest" },
      { 3: "GerardPiqué" },
      { 4: "RonaldAraújo" },
      { 5: "SergioBusquets" },
      { 7: "AntoineGriezmann" },
      { 8: "MiralemPjanić" },
      { 9: "MartinBraithwaite" },
      { 10: "LionelMessi(captain)" },
      { 11: "OusmaneDembélé" },
      { 12: "RiquiPuig" },
      { 13: "Neto" },
      { 14: "PhilippeCoutinho" },
      { 15: "ClémentLenglet" },
      { 16: "Pedri" },
      { 17: "FranciscoTrincão" },
      { 18: "JordiAlba" },
      { 19: "MatheusFernandes" },
      { 20: "SergiRoberto(4thcaptain)" },
      { 21: "FrenkiedeJong" },
      { 22: "AnsuFati" },
      { 23: "SamuelUmtiti" },
      { 24: "JuniorFirpo" },
    ],
  },
  {
    name: "Manchester United",
    founded: 1902,
    address: "Old Trafford",
    logo:
      "https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg",
    players: [
      { 1: "David de Gea" },
      { 2: "Victor Lindelöf" },
      { 3: "Eric Bailly" },
      { 4: "Phil Jones" },
      { "5 ": "Harry Maguire (captain)[194]" },
      { "6 ": "Paul Pogba" },
      { "7 ": "Edinson Cavani" },
      { "8 ": "Juan Mata" },
      { "9 ": "Anthony Martial" },
      { "10 ": "Marcus Rashford" },
      { "11 ": "Mason Greenwood" },
      { "13 ": "Lee Grant" },
      { 17: "Fred" },
      { 18: "Bruno Fernandes" },
      { 19: "Amad Diallo" },
      { 21: "Daniel James" },
      { 22: "Sergio Romero" },
      { 23: "Luke Shaw" },
      { 26: "Dean Henderson" },
      { 27: "Alex Telles" },
      { 29: "Aaron Wan-Bissaka" },
      { 31: "Nemanja Matić" },
      { 33: "Brandon Williams" },
      { 34: "Donny van de Beek" },
      { 38: "Axel Tuanzebe" },
      { 39: "Scott McTominay" },
      { 48: "Will Fish" },
      { 56: "Anthony Elanga" },
      { 74: "Shola Shoretire" },
    ],
  },
];

function TeamsReducer(state = { teams: data }, action) {
  switch (action.type) {
    case "CHANGE_TEAMS":
      var TeamsData = state.teams || [];
      TeamsData[action.payload["id"]] = action.payload["team"];
      return {
        ...state,
        teams: TeamsData,
      };
    default:
      return state;
  }
}

export default TeamsReducer;
